version: '3'
services:
  python3:
    restart: always
    build:
      dockerfile: './docker/python/Dockerfile'
    container_name: 'python3'
    working_dir: '/root/'
    tty: true
    volumes:
      - ./opt:/root/opt
  jupyterlab:
    build:
      dockerfile: './docker/jupyter/Dockerfile'
    container_name: jupyterlab
    ports:
      - "8888:8888"
    volumes:
      - ./jupyter-workspace:/app
    environment:
      - JUPYTER_ENABLE_LAB=yes

